AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'tmp/**/*'
    - 'vendor/bundle/**/*'

Layout/ClosingHeredocIndentation:
  Enabled: false

Metrics/ClassLength:
  Max: 125

Metrics/BlockLength:
  Max: 30
  Exclude:
    - 'spec/**/*_spec.rb'

Metrics/MethodLength:
  Max: 25

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Exclude:
    - 'lib/thredded_create_app/tasks/*/*.rb'
